#!/bin/sh

# Mount the /proc and /sys filesystems.
# You can omit this if you like. Just seemed nice to have.
mount -t proc none /proc
mount -t sysfs none /sys

# Load shell, which should now be soft linked to busybox
exec /bin/sh
